Name:           perl-Imager
Version:        1.015
Release:        4%{?dist}_rh7_no_gif_no_t1
Summary:        Perl extension for Generating 24 bit Images
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Imager/
Source0:        http://www.cpan.org/modules/by-module/Imager/Imager-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Exporter) >= 5.57
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Parse::RecDescent)
BuildRequires:  perl(Scalar::Util) >= 1.00
BuildRequires:  perl(Test::More)
BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  libpng-devel
BuildRequires:  libtiff-devel
#BuildRequires:  giflib-devel ### Not supported on RedHat 7 ###
BuildRequires:  libjpeg-devel
BuildRequires:  freetype-devel
#BuildRequires:  t1lib-devel  ### Not supported on RedHat 7 ###
Requires:       libpng libtiff libjpeg freetype
Requires:       perl(Exporter) >= 5.57
Requires:       perl(Parse::RecDescent)
Requires:       perl(Scalar::Util) >= 1.00
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(Imager::Font::T1)

%description
Imager is a module for creating and altering images. It can read and
write various image formats, draw primitive shapes like lines,and
polygons, blend multiple images together in various ways, scale, crop,
render text and more.

%prep
%setup -q -n Imager-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc adobe.txt apidocs.perl bigtest.perl Changes Changes.old combine.im compose.im convert.im conv.im doco.perl errep.perl filterlist.perl filters.im flip.im gaussian.im META.json paste.im README regops.perl render.im rotate.im rubthru.im scale.im spot.perl transform.perl trim.im typemap.local typemap.oldperl
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Imager*
%{_mandir}/man3/*

%changelog
* Mon May 23 2022 Michael R. Davis <mrdvt@cpan.org> 1.015-4
- Specfile autogenerated by cpanspec 1.78.
